### ISSUE TITLE
Compiling and running on Linux

### ISSUE THREAD

**Issue by olegklimov** [godlikepanos/anki-3d-engine#9] opened 2016-10-23 00:41 UTC
Hello @godlikepanos, I see you tried to minimize effort to build your 3d engine. Front page says "a great effort was made to ease the building process".

I have Ubuntu 16.04, failed to run a sample. First, please mention "git --recursive", it's not very clear how "thirdparty" directory works. Second, it's not obvious where `simple_scene` should be run from. I've ended up with tree symbolic links in `samples/simple_scene`:

```
engine_data
samples
shaders
```

But that's solvable. Where I'm stuck is

```
[E] Ppline error log follows (vs:90, fs:89):
Link info
---------
error: Type mismatch between variable "in_uv" matched by location "0"
 (anki-3d-engine/src/anki/gr/gl/PipelineImpl.cpp:199 createGlPipeline)
[E] Error in rendering thread. Aborting (anki-3d-engine/src/anki/gr/gl/RenderingThread.cpp:237 threadLoop)
```

Pretty sure it's a build or run issue, not an error in the code. 

Hope it helps to improve!

**Comment by godlikepanos** [comment] 2016-10-24 07:16
Hi Oleg,

Thanks for the report and the feedback.

- About git stuff. I'll make it a bit more clear or create a simple script.
- The samples must run from within the samples directory. I've updated the README.

Now to the more interesting. The Ppline error is caused by a glLinkProgram(). I've seen that error before on nVidia. It was a bug that I had to workaround. What drivers are you using? Is it possible to pull from the latest branch and try again (git pull && git submodule foreach git pull)?

Thanks for your help!

**Comment by olegklimov** [comment] 2016-10-24 22:15
```bash
anki-3d-engine/samples$ ls
assets
CMakeLists.txt
simple_scene

anki-3d-engine/samples$ /yada/anki-3d-engine/build/samples/simple_scene/simple_scene 
[I] Initializing application (version 0.1, build release Oct 25 2016, commit 3b7f1f0)... (anki-3d-engine/src/anki/core/App.cpp:162 initInternal)
[I] Creating SDL window (anki-3d-engine/src/anki/core/NativeWindowSdl.cpp:28 init)
[I] SDL window created (anki-3d-engine/src/anki/core/NativeWindowSdl.cpp:81 init)
[I] Creating GL 4.5 context... (anki-3d-engine/src/anki/gr/gl/GrManagerImplSdl.cpp:40 createContext)
[I] OpenGL async thread started: OpenGL version 4.5.0 NVIDIA 367.44, GLSL version 4.50 NVIDIA (anki-3d-engine/src/anki/gr/gl/RenderingThread.cpp:156 prepare)
[I] GPU vendor is NVIDIA (anki-3d-engine/src/anki/gr/gl/GlState.cpp:108 initRenderThread)
[I] Adding new data path "." (anki-3d-engine/src/anki/resource/ResourceFilesystem.cpp:215 init)
[I] Adding new data path ".." (anki-3d-engine/src/anki/resource/ResourceFilesystem.cpp:215 init)
[E] Directory is empty: ../assets (anki-3d-engine/src/anki/resource/ResourceFilesystem.cpp:307 addNewPath)
[E] App initialization failed (anki-3d-engine/src/anki/core/App.cpp:131 init)
[E] Error reported. To run anki-3d-engine/build/samples/simple_scene/simple_scene you have to navigate to the /path/to/anki/samples. And then execute it (anki-3d-engine/samples/simple_scene/Main.cpp:163 main)
```

Looks like `../assets` doesn't exist. I think your idea "Adding new path" for `.`, `..` is great, so sample will work from anywhere, it's just some bug there: it doesn't try `.`.

**Comment by olegklimov** [comment] 2016-10-24 22:24
Startup error is the same:

```
[E] Ppline error log follows (vs:90, fs:89):
Link info
---------
error: Type mismatch between variable "in_uv" matched by location "0"
```

I have:

Ubuntu 16.04.1 LTS
OpenGL version string: 4.5.0 NVIDIA 367.44

It's more or less latest NVidia drivers (released August), I have nothing unusual in this linux box.

(I'm looking for 3d engine for robotics simulation, need sane C++ interface, shadows, performance and no dependencies; already have basic render.)

**Comment by godlikepanos** [comment] 2016-10-25 07:24
Hmmm, I don't understand why it reports "vs:90, fs:89". When I run it goes up to 88. Is it possible to build with -DANKI_DEBUG=ON? If you run again it will dump the shaders in ~/.anki/cache. The if you don't mind pasting me the 00089.vert and 00090.vert here?

Thanks again and sorry for the trouble.

**Comment by olegklimov** [comment] 2016-10-25 12:00
Sorry I'm noob in shaders :(  Have no idea how to parse them from command line. I'll attach 89 and 90 files and leave it there. Hope it helps!

[89-90.zip](https://github.com/godlikepanos/anki-3d-engine/files/550507/89-90.zip)

Oleg.

**Comment by godlikepanos** [comment] 2016-10-25 13:05
Thanks for the shaders. It's definitely a problem that I've seen before. See https://devtalk.nvidia.com/default/topic/929076/opengl/nvidia-update-breaks-shader/. I was experiencing this problem with 364.19. I'm 95% this is a driver bug. The in_uv is vec2 in the vert shader and vec2 in the frag shader. Same precision as well. Doesn't make any sense to me. At the moment I'm using the 370.xx beta that's why I haven't seen the problem lately.

Nevertheless I'll try to workaround it tonight and let you know.

Once again thanks!

**Comment by olegklimov** [comment] 2016-10-25 20:24
Same error :(  Now location "1".

```
error: Type mismatch between variable "in_uv" matched by location "1"
```

**Comment by olegklimov** [comment] 2016-10-25 20:56
It kind of works. I see one room, yellowish grey, strange dot pattern on walls, blinky lights on every wall. Lights change as a pan horizontally, like 5 degrees to fade and appear again. Doesn't look to me it was intended this way.
![screenshot from 2016-10-25 23-53-15](https://cloud.githubusercontent.com/assets/18546213/19703985/a21af854-9b0e-11e6-89dc-14432e715fd9.jpg)

**Comment by godlikepanos** [comment] 2016-10-25 21:03
What you see is correct. The dots are a noise pattern that is added to the shadows and the flickering is caused by the low resolution of the normals. Currently the renderer is "allergic" to flat and single coloured surfaces. I might as well fix both the issues but I'll have to do that tomorrow.

**Comment by godlikepanos** [comment] 2016-11-25 16:33
Will close this ticket. It was more difficult than expected to fix the normals.

**Closed by godlikepanos** 2016-11-25 16:33 UTC
Labels: bug
